version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - mvn test -Dsurefire.excludes=**/PostgresIntegrationTests.java
      - docker build -t petclinic:$CODEBUILD_BUILD_NUMBER .
      - docker tag petclinic:$CODEBUILD_BUILD_NUMBER $ECR_REPO:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $ECR_REPO:$CODEBUILD_BUILD_NUMBER
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'